### ISSUE TITLE
Prevent Modal "Close" if accidentally clicked outside of the box. 

### ISSUE THREAD

**Issue by wucherpfennig** [cristidraghici/Kanext#10]
**Still great RELEASE**

### Actual behaviour

* If you are typing / creating anything involving a Modal dialogue chances are high that you accidentally click outside of the modal' box. With this you loose everything you just typed.

**I do not know wether this is an issue of this plugin / theme or from _GreenWing_**

### Expected behaviour

* Prevent data / work loss by disabling this behaviour. Only use the close button for closing stuff.

### Steps to reproduce

* ENABLE "GENERAL KANBOARD FIXES"  
  (BTW what does this mean?)
* Create anything with a Modal / Pop. Click outside the boundaries.

![image](https://user-images.githubusercontent.com/3634653/80524437-e4318280-898f-11ea-9029-d6bd5b946e90.png)

### Configuration

- Plugin version: 3.0
- Kanboard version: 1.2.14
- Database type and version: MySQL
- PHP version: 7.2
- OS: Linux
- Browser: Chrome

**Comment by cristidraghici** [comment]
I think the latest updates help with this problem.

**Comment by wucherpfennig** [comment]
Great, updated, verified and it works as intended. Thank you!
