### ISSUE TITLE
Change Version Requirements

### ISSUE THREAD

**Issue by wucherpfennig** [cristidraghici/Kanext#2]
Please change in Plugin.php the version requirements from "<=" to ">=".

Otherwise the plugin won't load in the latest versions.

BR

**Comment by cristidraghici** [comment]
Hello,

I have merged the pull request, but this was not a mistake. This is a dirty and hacky :) project which does not follow the guidelines of Kanboard and was aimed just to quickly provide something I needed. Therefore, I intended to enforce a check with every new release of Kanboard.

In future versions, this will be documented better. 🤞 😄
