### ISSUE TITLE
Bigboard requirement not documented

### ISSUE THREAD

**Issue by almereyda** [cristidraghici/Kanext#4]
This plugin/theme (rightfully) introduces a Bigboard button to the menu bar.

Until this plugin is not installed, this will lead to an error.

Also Bigboard is not maintained anymore and needs help https://github.com/stinnux/kanboard-bigboard/issues/20.

**Comment by cristidraghici** [comment]
Bigboard is not required anymore. Thank you for contributing and I hope you like the new version better. Have a nice day!
