### ISSUE TITLE
With Wiki plugin: Warning: filemtime(): stat failed

### ISSUE THREAD

**Issue by almereyda** [cristidraghici/Kanext#5]
When using the Wiki plugin https://github.com/funktechno/kanboard-plugin-wiki/, displaying a Wiki page with editions (versions) yields

> Warning: filemtime(): stat failed for plugins/Kanext/Skins/itcafe.css in /var/www/app/app/Helper/AssetHelper.php on line 37

**Comment by cristidraghici** [comment]
I think this issue has been fixed with the newer versions. Can you please confirm?

**Comment by almereyda** [comment]
Yes, this does not happen anymore.
